### ISSUE TITLE
Spike: See if it's possible to create a template for new issues in github projects

### ISSUE THREAD

**Issue by cstroliadavis** [qwik-resume/qwik-resume#10]
# User Story:

As a product owner, I find that I'm frequently adding many of the same elements to each new issue, such as `User Story` and `Acceptance Criteria`, and there's a good chance that we will find reason to add even more recurring items. It would be good if it's possible to have these already available in the ticket at the time of creation so all we need to do is fill them in.

# Acceptance Criteria:

Check to see if it is possible in github to create a template for creating new tickets. Ideally, we could select from different types of templates, however, that may be a bit pie in the sky. Would be good to know if it's possible, however. 

If templates are not possible, is it possible to add custom fields for these things?

Please provide information, guidance and recommendations.

**Comment by btleffler** [comment]
@cstroliadavis If you haven't already figured this one out, you can go into the repo settings to create multiple new issue templates. I believe you have to be the repo owner in order to set them up.

**Settings -> General -> Features -> Issues -> Setup Templates**
![Screenshot 2023-07-14 at 2 58 29 PM](https://github.com/qwik-resume/qwik-resume/assets/665794/96e173b3-3119-43fd-bc33-95d126159c03)

**Comment by cstroliadavis** [comment]
That's perfect, I think this pretty much answers the spike. I'll assign it to you and move it to done. TYSM.
